# Generated by Django 3.0.3 on 2020-08-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='D3_js',
            fields=[
                ('figure_no', models.AutoField(primary_key=True, serialize=False)),
                ('library_name', models.CharField(max_length=255)),
                ('heading', models.TextField(unique=True)),
                ('description', models.TextField()),
                ('js_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='D3_react_js',
            fields=[
                ('figure_no', models.AutoField(primary_key=True, serialize=False)),
                ('library_name', models.CharField(max_length=255)),
                ('heading', models.TextField(unique=True)),
                ('description', models.TextField()),
                ('js_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='React_js',
            fields=[
                ('figure_no', models.AutoField(primary_key=True, serialize=False)),
                ('library_name', models.CharField(max_length=255)),
                ('heading', models.TextField(unique=True)),
                ('description', models.TextField()),
                ('js_code', models.TextField()),
            ],
        ),
    ]
