# Generated by Django 3.0.3 on 2020-08-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs_viz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='d3_js',
            options={'ordering': ['figure_no', 'library_name', 'heading']},
        ),
        migrations.AlterModelOptions(
            name='d3_react_js',
            options={'ordering': ['figure_no', 'library_name', 'heading']},
        ),
        migrations.AlterModelOptions(
            name='react_js',
            options={'ordering': ['figure_no', 'library_name', 'heading']},
        ),
        migrations.AddField(
            model_name='d3_js',
            name='author',
            field=models.CharField(default='Mohit Gupta', max_length=255),
        ),
        migrations.AddField(
            model_name='d3_js',
            name='notes',
            field=models.TextField(default='Please enter some notes'),
        ),
        migrations.AddField(
            model_name='d3_react_js',
            name='author',
            field=models.CharField(default='Mohit Gupta', max_length=255),
        ),
        migrations.AddField(
            model_name='d3_react_js',
            name='notes',
            field=models.TextField(default='Please enter some notes'),
        ),
        migrations.AddField(
            model_name='react_js',
            name='author',
            field=models.CharField(default='Mohit Gupta', max_length=255),
        ),
        migrations.AddField(
            model_name='react_js',
            name='notes',
            field=models.TextField(default='Please enter some notes'),
        ),
        migrations.AlterUniqueTogether(
            name='d3_js',
            unique_together={('figure_no', 'library_name', 'heading')},
        ),
        migrations.AlterUniqueTogether(
            name='d3_react_js',
            unique_together={('figure_no', 'library_name', 'heading')},
        ),
        migrations.AlterUniqueTogether(
            name='react_js',
            unique_together={('figure_no', 'library_name', 'heading')},
        ),
    ]
